config/routes.rb
Rails.application.routes.draw do
  root 'static#index'
  get 'static/index'

  get 'static/about'

  get 'static/faq'

  resources :pokemons
  get 'secret_stuff/public_page'
  get 'secret_stuff/secret_page'

  resources :users
  get 'login', to: 'sessions#new'
  delete 'logout', to: 'sessions#destroy'
  resources :sessions, only: [:create]
  
end

app/models/pokemon.rb
class Pokemon < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
    has_secure_password
    validates :email, presence:true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  helper_method :current_user
  helper_method :user_logged_in?
  
  def current_user
    @current_user  ||= User.find(session[:user_id]) if session[:user_id]
  end
  
  def user_logged_in?
    current_user.present?
  end
  
  def authenticate_user
    unless user_logged_in?
      flash[:error] = "You must log in first."
      redirect_to login_path
  end
  end
  
end

app/controllers/pokemons_controller.rb
class PokemonsController < ApplicationController
  before_action :set_pokemon, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user, only: [ :edit, :update, :destroy]
  
  # GET /pokemons
  # GET /pokemons.json
  
  def index
    @pokemons = Pokemon.all
  end

  # GET /pokemons/1
  # GET /pokemons/1.json
  def show
  end

  # GET /pokemons/new
  def new
    @pokemon = Pokemon.new
  end

  # GET /pokemons/1/edit
  def edit
  end

  # POST /pokemons
  # POST /pokemons.json
  def create
    @pokemon = Pokemon.new(pokemon_params)

    respond_to do |format|
      if @pokemon.save
        format.html { redirect_to @pokemon, notice: 'Pokemon was successfully created.' }
        format.json { render :show, status: :created, location: @pokemon }
      else
        format.html { render :new }
        format.json { render json: @pokemon.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pokemons/1
  # PATCH/PUT /pokemons/1.json
  def update
    respond_to do |format|
      if @pokemon.update(pokemon_params)
        format.html { redirect_to @pokemon, notice: 'Pokemon was successfully updated.' }
        format.json { render :show, status: :ok, location: @pokemon }
      else
        format.html { render :edit }
        format.json { render json: @pokemon.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pokemons/1
  # DELETE /pokemons/1.json
  def destroy
    @pokemon.destroy
    respond_to do |format|
      format.html { redirect_to pokemons_url, notice: 'Pokemon was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pokemon
      @pokemon = Pokemon.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pokemon_params
      params.require(:pokemon).permit(:name, :desc, :height, :weight, :category, :ability, :type, :weakness, :hp, :attack, :defence, :special_attack, :special_defence, :speed, :image_url_large, :image_url_small)
    end
end

app/controllers/secret_stuff_controller.rb
class SecretStuffController < ApplicationController
  
  before_action :authenticate_user, only: :secret_page
  
  def public_page
  end

  def secret_page
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    render "new"
  end

  def create
    user=User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path
    else
      flash.now.alert ="Invalid login details."
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def index
  end

  def about
  end

  def faq
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pokemons_helper.rb
module PokemonsHelper
end

app/helpers/secret_stuff_helper.rb
module SecretStuffHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/statics_helper.rb
module StaticsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.min.js"></script>
  <script src="http://code.highcharts.com/highcharts.js"></script>
  <script src="http://code.highcharts.com/modules/exporting.js"></script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application' %>
  <%= javascript_include_tag "highcharts.js", "chartkick" %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">  

<% if user_logged_in? %>
<h3>Hello, <%= current_user.name %></h3>
  <%= link_to "Logout", logout_path, method: :delete %>
<% else %>
  <%= link_to "Login", login_path %> |
  <%= link_to "Sign Up", new_user_path %>
<% end %>

 | <%= link_to "Home", root_path %> |
<%= link_to "Pokemons!!", pokemons_path %> |
<%= link_to "About", static_about_path %> |
<%= link_to "FAQ", static_faq_path %> 

<div class = "row">
    <div class="col-sm-2"></div>
    <div class="col-sm-8">
      <% flash.each do |name, message| %>
      <div class ="flash-message flash-message-<%= name %>" >
      <%= message %>
      </div>
      <% end %>
  </div>
  <div class="col-sm-2"></div>
</div>
  


<%= yield %>

</div>
</body>
</html>

app/views/pokemons/_form.html.erb
<%= form_for(@pokemon) do |f| %>
  <% if @pokemon.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pokemon.errors.count, "error") %> prohibited this pokemon from being saved:</h2>

      <ul>
      <% @pokemon.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :desc %><br>
    <%= f.text_field :desc %>
  </div>
  <div class="field">
    <%= f.label :height %><br>
    <%= f.text_field :height %>
  </div>
  <div class="field">
    <%= f.label :weight %><br>
    <%= f.text_field :weight %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :ability %><br>
    <%= f.text_field :ability %>
  </div>
  <div class="field">
    <%= f.label :variety %><br>
    <%= f.text_field :variety %>
  </div>
  <div class="field">
    <%= f.label :weakness %><br>
    <%= f.text_field :weakness %>
  </div>
  <div class="field">
    <%= f.label :hp %><br>
    <%= f.number_field :hp %>
  </div>
  <div class="field">
    <%= f.label :attack %><br>
    <%= f.number_field :attack %>
  </div>
  <div class="field">
    <%= f.label :defence %><br>
    <%= f.number_field :defence %>
  </div>
  <div class="field">
    <%= f.label :special_attack %><br>
    <%= f.number_field :special_attack %>
  </div>
  <div class="field">
    <%= f.label :special_defence %><br>
    <%= f.number_field :special_defence %>
  </div>
  <div class="field">
    <%= f.label :speed %><br>
    <%= f.number_field :speed %>
  </div>
  <div class="field">
    <%= f.label :image_url_large %><br>
    <%= f.text_field :image_url_large %>
  </div>
  <div class="field">
    <%= f.label :image_url_small %><br>
    <%= f.text_field :image_url_small %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pokemons/edit.html.erb
<h1>Editing Pokemon</h1>

<%= render 'form' %>

<%= link_to 'Show', @pokemon %> |
<%= link_to 'Back', pokemons_path %>

app/views/pokemons/index.html.erb
<p id="notice"><%= notice %></p>

<div class='container'>
  <h1>The Weird Pokemons</h1>
  <div class="row">
    <% @pokemons.each do |pokemon| %>
    <div class="col-sm-3">
    <div class="thumbnail">
      <%= link_to image_tag(pokemon.image_url_small), pokemon %>
      <div class="caption">
        <h3><%= pokemon.name %></h3>
        <p><%= pokemon.desc %></p>
        <p><%= link_to 'Show', pokemon %> <%= link_to 'Edit', edit_pokemon_path(pokemon) %> <%= link_to 'Destroy', pokemon, method: :delete, data: { confirm: 'Are you sure?' } %></p>
      </div>
    </div>
    </div>
    <% end %>
  </div>

<div class="row">
<%= link_to 'New Pokemon', new_pokemon_path %>
</div>

</div>

app/views/pokemons/new.html.erb
<h1>New Pokemon</h1>

<%= render 'form' %>

<%= link_to 'Back', pokemons_path %>

app/views/pokemons/show.html.erb
<p id="notice"><%= notice %></p>

<script>
         $(document).ready(function() {
    var chart1 = new Highcharts.Chart({
        chart: {
            renderTo: 'container',
            type: 'bar',
            backgroundColor: '#E0CCD5',
            style: {color: '#ffffff', fontSize: '16px'}
        },
        xAxis: {
            categories: ['Hp', 'Attack', 'Defence', 'Special Attack', 'Special Defence', 'Speed'],
            labels: {
                style: {
                    fontSize:'15px'
                }
            }
        },
        xYxis: {
            labels: {
                style: {
                    fontSize:'15px'
                }
            }
        },
        title: {
            text: 'Pokemon Stats'
        },
        series: [ {name: 'Levels', data: [ <%= @pokemon.hp %> , 
          <%= @pokemon.attack %>,
          <%= @pokemon.defence %>,
          <%= @pokemon.special_attack %>,
          <%= @pokemon.special_defence %>,
          <%= @pokemon.speed %>]
        }],
        legend: {
           enabled: false
        }
    });
});
          
        </script>

<div class='container'>
  <div class="row">
    <div class="col-sm-8">
      <center><h1><%= @pokemon.name %></h1></center>
    </div>
  </div>
  
  <div class="row">
    <div class="col-sm-5">
      <p>
        <%= image_tag(@pokemon.image_url_large) %>
      </p>
    </div>
    <div class="col-sm-5">
      <p><strong>Name: </strong><%= @pokemon.name %></p>
      <p><strong>Desc: </strong><%= @pokemon.desc %></p>
      <p><strong>Height: </strong><%= @pokemon.height %></p>
      <p><strong>Weight: </strong><%= @pokemon.weight %></p>
      <p><strong>Category: </strong><%= @pokemon.category %></p>
      <p><strong>Ability: </strong><%= @pokemon.ability %></p>
      <p><strong>Variety: </strong><%= @pokemon.variety %></p>
      <p><strong>Weakness: </strong><%= @pokemon.weakness %></p>

    </div>
    <div class="row">
      <div class="col-sm-12">
        <div id="container" style="width:100%; height:400px;"></div>
      </div>
    </div>
  
<br />
<div class="row">
  <div class="col-sm-8">
<%= link_to 'Edit', edit_pokemon_path(@pokemon) %> |
<%= link_to 'Back', pokemons_path %>
</div>
</div>
</div>

app/views/secret_stuff/public_page.html.erb
<h1>SecretStuff#public_page</h1>
<p>Find me in app/views/secret_stuff/public_page.html.erb</p>

app/views/secret_stuff/secret_page.html.erb
<h1>SecretStuff#secret_page</h1>
<p>Find me in app/views/secret_stuff/secret_page.html.erb</p>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Password digest</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.password_digest %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Password digest:</strong>
  <%= @user.password_digest %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>